/**
 * Standard restaurant categories — the single source of truth.
 * All restaurants should belong to one of these categories.
 * New categories can be added via the admin console's "Add New Category" flow,
 * but day-to-day editing should use this dropdown list to prevent typos.
 */
export const STANDARD_CATEGORIES: string[] = [
    "American",
    "Bakery",
    "Bars & Pubs",
    "BBQ",
    "Brazilian",
    "Breakfast & Brunch",
    "Burgers",
    "Cafes",
    "Chinese",
    "Coffee Shops",
    "Delis & Sandwiches",
    "Dessert",
    "Diners",
    "Donuts",
    "Fast Food",
    "Fine Dining",
    "Ice Cream",
    "Indian",
    "Italian",
    "Japanese",
    "Korean",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Pizza",
    "Ramen",
    "Restaurants",
    "Seafood",
    "Spanish",
    "Steakhouse",
    "Sushi",
    "Tacos",
    "Thai",
    "Turkish",
    "Vegan",
    "Vegetarian",
    "Vietnamese",
];
